# This File contains the main daemon runtime 
# to enable this file, add the filename to
# "COMPOSE_FILE" within .env

version: '2.1'
services:
    daemon:
      image: ccarney16/pterodactyl-daemon:latest
      ports:
      - 2022:2022
      - 8080:8080
      privileged: true
      restart: always
      volumes:
      - "/var/lib/pterodactyl/:/var/lib/pterodactyl/"
      - "/srv/daemon-data/:/srv/daemon-data/"
      - "/tmp/pterodactyl/:/tmp/pterodactyl/"
      - "/etc/timezone:/etc/timezone:ro"
    
      # Docker socket and directory, needed to communicate to docker
      # NOTE: If you are using docker in a different directory, please change below to reflect that!
      - ${DOCKER_ROOT:-/var/lib/docker}:${DOCKER_ROOT:-/var/lib/docker}
      - ${DOCKER_SOCKET:-/var/run/docker.sock}:${DOCKER_SOCKET:-/var/run/docker.sock}
