###
# Optional ProjectDependencies for Pterodactyl
#
# This compose file provides the required dependencies for 
# Pterodactyl, such as MariaDB and Redis.
##
version: '2.1'
services:
    mysql:
      image: mariadb:10.4
      env_file: ./conf.d/mariadb.env
      restart: always
      volumes: 
      - ./data/db:/var/lib/mysql
    redis:
      image: redis:alpine
      restart: always
